apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhookapi
  name: webhook-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: webhookapi
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhookapi-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: webhookCRole
  namespace: default
  labels:
    name: webhookCRole
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: webhook-rb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: webhookapi-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: webhookCRole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhookapi
  labels:
    app: webhookapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhookapi
  template:
    metadata:
      labels:
        app: webhookapi
    spec:
      containers:
      - name: webhookapi
        image: chaosnative/lp-webhookapp:ci
        ports:
        - containerPort: 8081
        env:
        - name: PORTAL_NAMESPACE
          value: "litmus"
        - name: FRONTEND_POD_LABEL
          value: "litmusportal-frontend"
        - name: BACKEND_POD_LABEL
          value: "litmusportal-server"
        - name: FRONTEND_DOCKER_REPO
          value: "litmusportal-frontend"
        - name: GQL_DOCKER_REPO
          value: "litmusportal-server"
        - name: AUTH_DOCKER_REPO
          value: "litmusportal-auth-server"
        - name: SLACK_WEBHOOK_LINK
          value: ""
      serviceAccountName: webhookapi-sa 